### ISSUE TITLE
Missing copy.py file on network-programmability-stream/netbox/ example

### ISSUE THREAD

**Issue by jcralbino** [dmfigol/network-programmability-stream#10]
Hello Dimitri

I am starting my journey in the network automation and i would like to thank you for the information you provide.
Indeed i believe it will help me reach a different level.

I have started by using your example to add devices to the netbox, that i am starting to configure in my organization, but it seems there is a missing dependeciy here. 
the helper.py file is using i believe another file copy.py that i was not able to find.

Can you assist me here

Regards
Jose

**Comment by dmfigol** [comment]
Hi Jose,
`copy` is a standard python module and doesn't need to be included in the project files.
